### ISSUE TITLE
Extended Sos is not included as tie-breaker

### ISSUE THREAD

**Issue by morphinepl** [morphinepl/ANRTournament#19]
Extended Sos is not included as tie-breaker

**Comment by morphinepl** [comment]
Function RefreshPointsTable:
`
IEnumerable<Player> sortedplayers = this.pointstable.OrderByDescending(p => p.Points)
                                                                .ThenByDescending(p => p.GroupPointWinner)
                                                                .ThenByDescending(p => p.Sos)
                                                                .ThenByDescending(p => p.Extsos)
                                                                .ThenByDescending(p => p.LastTieBreak);
`

**Comment by zaroth** [comment]
Should be fixed in 0.2.11. Please comment if the issue pops up again.
