### ISSUE TITLE
ExtSos Not correctly ordering players.

### ISSUE THREAD

**Issue by lpoulter** [morphinepl/ANRTournament#20]
![screenshot 2016-05-05 23 21 48](https://cloud.githubusercontent.com/assets/3940567/15060059/4ed03d16-131f-11e6-9c22-d12f98b36b8a.png)

**Comment by lpoulter** [comment]
Shouldn't Ben be 2nd here?

**Comment by tantauralus** [comment]
If I'm correct that is due to the error reported in Tickt #19 (ExtSoS is calculated and displayed but in the last release of the version not jet includet as a tiebreaker).

**Comment by zaroth** [comment]
Should be fixed in 0.2.11. Please comment if the issue pops up again.
