### ISSUE TITLE
Changes neede tue to new tournament regulations valid August 1st 2016

### ISSUE THREAD

**Issue by tantauralus** [morphinepl/ANRTournament#27]
Prestige Points will be changing August 1st 2016 as follows:

Tournament Points 
Players earn tournament points at the end of each round based on both games during the round. 
At the end of a tournament, the player with the most tournament points wins the 
tournament.
 In the case of a larger event, they are instead used to determine who makes the cut 
to double elimination rounds. For each game, players receive tournament points 
as follows: 
Game Win = 3 tournament points
Modified Game Win = 2 tournament points
Draw = 1 tournament point 
Game Loss = 0 tournament points

So sadly we will need some softwarechanges...

**Comment by Inermis2** [comment]
Also there is no Head to Head tiebreaker now.

**Comment by zaroth** [comment]
Thanks @tantauralus !
